# Generated by Django 4.1.7 on 2023-04-20 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelfrom', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Vser',
        ),
    ]
